const FastFoodSuggestions = [
  {
        categoryName: "Fast-Food",
        restaurantName: "Besiktas Burger King",
        foodName: "Big King",
        foodImage: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmVzdGF1cmFudCUyMGZvb2R8ZW58MHx8MHx8&w=1000&q=80", 
        restaurantImage: "https://cdn.getiryemek.com/products/1623327056988_500x375.jpeg", 
        restaurantRating: "4.7", 
        workingHours: "09.00-01.30", 
        price: "32$",
        rating: "4.2",
        tab: "Delivery", 
    }, 

     {
        categoryName: "Fast Food",
        restaurantName: "Papa John's",
        foodName: "Macaroni Pizza",
        foodImage: "https://cdn.getiryemek.com/restaurants/1581323800278_1125x522.jpeg",
        restaurantImage: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Papa_John%27s_Logo_2019.svg", 
        restaurantRating: "4.0",
        workingHours: "09.00-02.00",  
        price: "22$",
        rating: "4.4", 
        tab: "Pickup", 
    }, 
    {
        categoryName: "Fast Food",
        restaurantName: "Pizza Bulls",
        foodName: "Pepperoni Pizza",
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/pizza_bulls/pepperoni_big.jpg",
        restaurantImage: "https://lh3.googleusercontent.com/proxy/1PcENUZq1x_jdkXCc5eiOlwS4oVYstw3UTia86I-aIJdcEA2O6e35UAs6H08qvOPzk9q_QgQ6HCe4MiD0aLLMlVetZAZiZKuQ_D-Gw3_jg", 
        restaurantRating: "3.9",
        workingHours: "08.00-24.00",
        price: "29$",
        rating: "4.7", 
          tab: "Delivery", 
    }, 
]; 

const BakerySuggestions = [
       {   
        categoryName: "Bakery",
        restaurantName: "Panista",
        foodName: "Simit",
        foodImage: "https://iasbh.tmgrup.com.tr/6c39a4/650/344/0/145/1152/749?u=https://isbh.tmgrup.com.tr/sbh/2020/02/28/citir-citir-simit-tarifi-essiz-lezzetiyle-gevrek-simit-nasil-yapilir-1582879335217.jpg",
        restaurantImage: "http://cdn.yemeksepeti.com/CategoryImages/TR_ISTANBUL/panista3_big.gif",
        restaurantRating: "4.3",
        workingHours: "07.00-22.00",
        price: "2,00$",
        rating: "3.5", 
        tab: "Pickup", 
       },
        {
        categoryName: "Bakery",
        restaurantName: "Gültekin Pastanesi",
        foodName: "Firin Sütlaç",
        foodImage: "https://image.yemeksepeti.com/restaurant/istanbul/gultekin-pastanesi-bakirkoy-cevizlik-mah/firin-sutlac_big.jpg",
        restaurantImage: "http://4.bp.blogspot.com/-odedCxwVd2I/UWKsKfMA84I/AAAAAAAAAws/L3fwOYYixgM/s1600/g%C3%BCltekin+pastanesi.JPG",
        restaurantRating: "3.5", 
        workingHours: "06.00- 21.00",
        price: "19,50$", 
        rating: "3.8", 
        tab: "Pickup", 
    },
       {
        categoryName: "Bakery",
        restaurantName: "Cihan Pastaneleri",
        foodName: "İzmir Bomba",
        foodImage: "https://cdn.yemeksepeti.com//restaurant/TR_ISTANBUL/cihan-pastaneleri-besiktas-visnezade-mah-akaretler/izmir-bomba_big.jpg",
        restaurantImage: "https://lh5.googleusercontent.com/p/AF1QipNzNoLtJ-tVaHZZbOikG0xduXCpVwokvbEm01Ev",
        restaurantRating: "4.1", 
        workingHours: "06.00-20.00",
        price: "9,40$",
        rating: "4.9", 
        tab: "Delivery", 
    },
    {
        categoryName: "Bakery",
        restaurantName: "Nazar Pastanesi",
        foodName: "Ekler",
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/nazarpastanesi/ekleradet_20210726145608_big.jpg",
        restaurantImage: "https://nazarpastanesi.com/wp-content/uploads/2020/05/balli.jpg",
        restaurantRating: "4.6", 
        workingHours: "10.00-19.00",
        price: "6,35$",
        rating: "4.1", 
        tab: "Pickup", 
    },
    
]; 
const DessertSuggestions = [
       {
        categoryName: "Desserts",
        restaurantName: "Baklavaci Güllüoğlu",
        foodName: "Fistikli Baklava",
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/gulluoglu_baklavalari/fistiklibaklava4dilim_20210206030701_big.jpg",
        restaurantImage:"https://m.media-amazon.com/images/S/stores-image-uploads-na-prod/2/AmazonStores/ATVPDKIKX0DER/ff54a15bedc8c3f8065cde9afe4137bb.w408.h408.jpg",
        restaurantRating:"4.7", 
        workingHours: "12.00-24.00",
        price: "22,50$",
        rating: "4.9", 
        tab: "Delivery", 
    },
        {
        categoryName: "Desserts",
        restaurantName: "Horasan Ortaköy Waffle",
        foodName: "Waffle",
        foodImage: "https://media-cdn.tripadvisor.com/media/photo-p/14/f3/be/93/photo0jpg.jpg",
        restaurantImage: "http://cdn.yemeksepeti.com/CategoryImages/TR_ISTANBUL/horasan-ortakoy-waffle--kumpir-lcv1_big.gif", 
        restaurantRating: "3.9", 
        workingHours: "08.00-22.00",
        price: "22,50$",
        rating: "4.9", 
        tab: "Pickup", 
    },
        {
        categoryName: "Desserts",
        restaurantName: "Topraktan, Bornova",
        foodName: "Pavlova",
        foodImage: "https://egepazarindan.com/wp-content/uploads/2020/12/Ekran-Resmi-2020-12-29-15.58.13.png",
        restaurantImage: "https://topraktan.com.tr/static/img/slider3.jpg",
        restaurantRating: "5.0", 
        workingHours: "09.00-24.00",
        price: "17,50$",
        rating: "5.0", 
        tab: "Delivery", 
    },
]; 
const CoffeeSuggestions = [
    {
        categoryName: "Coffee",
        restaurantName: "Starbucks, Bebek",
        foodName: "Caramel Macchiato",
        foodImage: "https://www.starbucks.com.tr/media/caramel-macchiato_tcm95-64111_w1024_n.png",
        restaurantImage: "https://i.gazeteduvar.com.tr/2/1280/720/storage/files/images/2021/11/25/starbucks-J9Od_cover.jpg",
        restaurantRating:"4.1", 
        workingHours: "08.00-01.00",
        price: "22,50$",
        rating: "4.9",
        tab: "Pickup",  
    },

     {
        categoryName: "Coffee",
        restaurantName: "Kahve Dünyasi",
        foodName: "White Chocolate Mocha",
        foodImage: "https://www.kahvedunyasi.co.uk/CMSFiles/Product/LittleImage/dark-chocolate-mocha_636482237710605582.jpg",
        restaurantImage: "https://i.dunya.com/2/1280/720/storage/old/files/2020/9/29/483384/483384.jpg.webp",
        restaurantRating: "4.0", 
        workingHours: "08.00-01.00", 
        price: "18,50$",
        rating: "4.5",
        tab: "Delivery",  
    },
]; 

export {FastFoodSuggestions, BakerySuggestions, DessertSuggestions, CoffeeSuggestions};
