const Foods = [
    {
        description: "2 adet Hamburger eti, 3 katli özel ekmeği, cheddar peyniri",
        categoryName: "Fast-Food",
        restaurantName: "Besiktas Burger King",
        foodName: "Big King",
        foodImage: "https://www.burgerking.com.tr/cmsfiles/products/big-king-menu.png?v=177", 
        restaurantRating: "4.7", 
        workingHours: "09.00-01.30", 
        price: "32$",
        calories: "500,17",
        rating: "4.2",
        tab: "Delivery",
         
    },

    {
        foodName: "Whopper Menü",
        restaurantName: "Besiktas Burger King", 
        foodImage: "https://www.burgerking.com.tr/cmsfiles/products/whopper-menu.png?v=177", 
        price: "$30",  
        description: "Whopper® eti, büyük boy susamli sandviç ekmeği, salatalik turşusu, ", 
        calories: "675,47", 
    },

    {
        foodName: "Etli Barbekü Brioche Menü",
        foodImage: "https://www.burgerking.com.tr/cmsfiles/products/etli-barbeku-brioche-menu.png?v=177", 
        restaurantName: "Besiktas Burger King", 
        price: "$24", 
        description: "Whopper® eti, enfes brioche ekmeği, cheddar peyniri", 
        calories: "767,57", 
    },
    {
        foodName: "Double Texas Smokehouse Burger Menü", 
        foodImage: "https://www.burgerking.com.tr/cmsfiles/products/double-texas-smokehouse-burger-menu.png?v=177", 
        restaurantName: "Besiktas Burger King", 
        price: "$33", 
        description: "2 kat Whopper® eti, füme eti, barbekü sosu", 
        calories: "1111,80", 
    },
   
  
    {
        foodName: "Büyük Boy Pepperoni Pizza", 
        restaurantName: "Pizza Bulls",  
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/pizza_bulls/pepperoni_big.jpg", 
        description: "büyük boy pepperoni pizza", 
        calories:"567,23",
        price: "$29", 
    },
    {
        foodName: "Büyük Boy Pizza + 2 Adet Sos", 
        restaurantName: "Pizza Bulls", 
        foodImage: "https://cdn.yemeksepeti.com//ProductImages/TR_ISTANBUL/pizza_bulls/buyukboypizzaa_big.jpg", 
        price: "$41", 
        description: "büyük boy pizza + 2 adet dilediğin sos", 
        calories:  "497", 
    },

    {
        foodName: "Çitir Tavuk Menü",
        foodImage: "https://cdn.yemeksepeti.com//ProductImages/TR_ISTANBUL/pizza_bulls/citirtavukmenuu_big.jpg",
        restaurantName: "Pizza Bulls",
        description:"çitir tavuk ve elma patates menü" , 
        calories: "494,13", 
        price: "$43"
    }
    ,
    {
        foodName: "Macaroni Pizza", 
        foodImage: "https://cdn.getiryemek.com/restaurants/1581323800278_1125x522.jpeg",
        description: "peynirli, macaroni pizza", 
        restaurantName:  "Papa John's",
        calories: "375,43", 
        price: "$22",
    },
    {
        foodName: "BBQ Sos Tavuk Büyük", 
        foodImage: "https://media-cdn.tripadvisor.com/media/photo-s/1a/e9/dc/4c/barbeku-soslu-tavuklu.jpg",
        restaurantName: "Papa John's", 
        description: "barbekü soslu tavuklu büyük boy pizza",
        calories: "643,12", 
        price: "$33", 
    },
    {
        foodName: "Akdeniz Pizza", 
        foodImage: "https://cdn.getiryemek.com/products/1582792101790_500x375.png", 
        restaurantName: "Papa John's", 
        description: "zeytinli, sucuklu, salamli akdeniz pizza", 
        calories: "432,49" ,
        price: "$27", 
    },
    {
        foodName: "Quattro Fromaggi", 
        foodImage: "https://www.papajohns.com.tr/upload/big/image611e1ef09d4cf.jpg", 
        restaurantName: "Papa John's", 
        description: "salamli, sosisli, küçük boy italyan pizza", 
        calories: "344,45", 
        price: "$28", 
    },
    {
        foodName: "İzmir Bomba",
        foodImage: "https://cdn.yemeksepeti.com//restaurant/TR_ISTANBUL/cihan-pastaneleri-besiktas-visnezade-mah-akaretler/izmir-bomba_big.jpg",  
        restaurantName:"Cihan Pastaneleri", 
        description: "çikolatali, sicak izmir bomba", 
        calories: "475,34", 
        price: "$5", 
    },
    {
        foodName: "Makaron", 
        foodImage: "https://www.uzaypastanesi.com/images/category/mini_Untitled%20Capture0076_Todp.jpg", 
        restaurantName: "Cihan Pastaneleri",
        description: "çeşitli renklerde tatli makaron",
        calories: "120,34", 
        price: "$4", 
    },
    {
        foodName: "Tereyağli Kruvasan", 
        foodImage:  "https://www.uzaypastanesi.com/images/product/tereya%C4%9Fl%C4%B1%20kruvasan-min_5ytR.jpg", 
        restaurantName: "Cihan Pastaneleri",
        description: "bol tereyağli, sicak, çitir kruvasan", 
        calories: "230,345", 
        price: "$9",
    },
     {
        foodName: "Simit", 
        foodImage:  "https://iasbh.tmgrup.com.tr/6c39a4/650/344/0/145/1152/749?u=https://isbh.tmgrup.com.tr/sbh/2020/02/28/citir-citir-simit-tarifi-essiz-lezzetiyle-gevrek-simit-nasil-yapilir-1582879335217.jpg", 
        restaurantName: "Panista",
        description: "çitir gevrek simit", 
        calories: "45,34", 
        price: "$2",
    },
     {
        foodName: "Baget Ekmeği", 
        foodImage: "https://panista.com.tr/wp-content/uploads/2021/05/baget-897x897.jpg",
        restaurantName: "Panista", 
        price: "$3", 
        description: "1/3 baget ekmeği", 
        calories: "100",
    },
      {
        foodName: "Çikolatali Kruvasan",
        restaurantName: "Panista", 
        foodImage: "https://panista.com.tr/wp-content/uploads/2021/01/nutelallikruvasan-897x505.jpg", 
        price: "$5" ,
        description: "çikolatali çitir kruvasan", 
        calories: "150",
    },
     {
        foodName: "Tereyağli Kruvasan", 
        foodImage:  "https://www.uzaypastanesi.com/images/product/tereya%C4%9Fl%C4%B1%20kruvasan-min_5ytR.jpg", 
        restaurantName: "Panista",
        description: "bol tereyağli, sicak, çitir kruvasan", 
        calories: "230,345", 
        price: "$9",
    },
        {

        restaurantName: "Gültekin Pastanesi",
        foodName: "Firin Sütlaç",
        description: "nefis firin sütlaç",
        foodImage: "https://image.yemeksepeti.com/restaurant/istanbul/gultekin-pastanesi-bakirkoy-cevizlik-mah/firin-sutlac_big.jpg",
        price: "19,50$",
        calories: "308,45",

    },
      {
        foodName: "Tuzlu Kurabiye", 
        foodImage:  "https://www.uzaypastanesi.com/images/category/mini_tuzlu%20kurabiye_Qyxr.jpg", 
        restaurantName: "Gültekin Pastanesi",
        description: "karişik tuzlu kurabiye", 
        calories: "30,345", 
        price: "$9",
    },
      {
        foodName: "Kepekli Galeta", 
        foodImage:  "https://www.uzaypastanesi.com/images/product/mini_kepekli%20galeta_M_wh.jpg", 
        restaurantName: "Gültekin Pastanesi",
        description: "kepekli çitir galeta", 
        calories: "45,345", 
        price: "$7",
    },
      {
        foodName: "Çitir Zeytinli Poğaça", 
        foodImage: "https://www.uzaypastanesi.com/images/product/mini_%C3%A7%C4%B1t%C4%B1r%20zeytinli%20po%C4%9Fa%C3%A7a_mzvC.jpg",
        restaurantName: "Gültekin Pastanesi",
        description: "mini mayali zeytinli poğaça", 
        calories: "20,111", 
        price: "$4",
    },
       {
        restaurantName: "Nazar Pastanesi",
        foodName: "Ekler",
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/nazarpastanesi/ekleradet_20210726145608_big.jpg",
        price: "6,35$",
        description: "büyük leziz ekler",
        calories: "45,70",
    },
       {
        foodName: "San Sebastian", 
        foodImage:"https://www.uzaypastanesi.com/images/product/mini_sebastian_jGQO_5UFJ.jpg",
        restaurantName: "Nazar Pastanesi",
        description: "Bütün San Sebastian Cheesecake", 
        calories: "150,445", 
        price: "$49",
    },
       {
        foodName: "Browni Cheesecake", 
        foodImage: "https://www.uzaypastanesi.com/images/product/mini_karamelli%20c.cake_gI73_SMWl.jpg",
        restaurantName: "Nazar Pastanesi",
        description: "Karamelli Brownie Cheesecake", 
        calories: "190,111", 
        price: "$51",
    },
       {
        foodName: "Profiterol",
        foodImage: "https://www.uzaypastanesi.com/images/product/mini_PROF_MRFp_9YBz_7tHx.jpg", 
        restaurantName: "Nazar Pastanesi",
        description: "leziz profiterol", 
        calories: "100,111", 
        price: "$19",
    },
        {
        restaurantName: "Baklavaci Güllüoğlu",
        foodName: "Fistikli Baklava",
        foodImage: "https://cdn.yemeksepeti.com/ProductImages/TR_ISTANBUL/gulluoglu_baklavalari/fistiklibaklava4dilim_20210206030701_big.jpg",
        price: "22,50$",
        description: "çitir fistikli baklava",
        calories: "734,5", 
    },
       {
        foodName: "Cevizli Köy Baklava",
        foodImage: "https://www.uzaypastanesi.com/images/product/mini_koy%20baklavasi_TFHg.jpg",
        restaurantName: "Baklavaci Güllüoğlu",
        description: "leziz çitir cevizli baklava", 
        calories: "1403,111", 
        price: "$25",
    },
       {
        foodName: "Özel Tepsi Su Böreği",
        foodImage: "https://www.uzaypastanesi.com/images/product/su-b%C3%B6re%C4%9Fi-tepsi_S8d6.jpg",
        restaurantName: "Baklavaci Güllüoğlu",
        description: "çitir su böreği", 
        calories: "70,145", 
        price: "$14",
    },
          {
        restaurantName: "Topraktan, Bornova",
        foodName: "Pavlova",
        foodImage: "https://egepazarindan.com/wp-content/uploads/2020/12/Ekran-Resmi-2020-12-29-15.58.13.png",
        restaurantRating: "5.0", 
        price: "17,50$",
        calories: "130,69", 
    },
        {
        foodName: "Çilekli Beyaz",
        foodImage: "https://topraktan.com.tr/media/cache/b6/3b/b63bb67f56b5c0e567426c16a8d88d1d.jpg",
        restaurantName: "Topraktan, Bornova",
        description: "nefis çilekli pasta", 
        calories: "140,145", 
        price: "$32",
    },
    {
        foodName: "Limon Bademli",
        foodImage: "https://topraktan.com.tr/media/cache/af/1f/af1f88a8796f20f4c98898df2411e372.jpg",
        restaurantName: "Topraktan, Bornova",
        description: "nefis limonlu bademli pasta", 
        calories: "170,145", 
        price: "$30",
    },
    {
        restaurantName: "Horasan Ortaköy Waffle",
        foodName: "Waffle",
        foodImage: "https://media-cdn.tripadvisor.com/media/photo-p/14/f3/be/93/photo0jpg.jpg",
        price: "22,50$",
        description: "bol malzemeli sicak waffle", 
        calories: "346,6", 
        
    },
    {
        restaurantName: "Horasan Ortaköy Waffle",
        foodName: "Karişik Gözleme",
        foodImage: "https://cdn.yemek.com/mnresize/940/940/uploads/2015/06/gozleme-tarifi-yeni.jpg", 
        price: "15,50$",
        description: "patatesli, kiymali gözleme", 
        calories: "200,6", 
        
    },
       {
        restaurantName: "Horasan Ortaköy Waffle",
        foodName: "Kumpir",
        foodImage: "https://mutfaktaki.com/wp-content/uploads/2020/11/Evde-Kumpir-Nasil-Yapilir.jpeg",
        price: "23,30$",
        description: "Patates, havuç, turşu, misir, zeytin, kaşar peyniri ve tereyaği", 
        calories: "140", 
        
    },
    {
        restaurantName: "Starbucks, Bebek",
        foodName: "Caramel Macchiato",
        foodImage: "https://www.starbucks.com.tr/media/caramel-macchiato_tcm95-64111_w1024_n.png", 
        price: "22,50$",
        description: "Süt, Demlenmiş Espresso, Vanilya Şurubu", 
        calories: "95,34" ,
    },
       {
        restaurantName: "Starbucks, Bebek",
        foodName: "White Chocolate Mocha",
        foodImage: "https://www.starbucks.com.tr/media/White_Chocolate_Mocha_tcm95-64109_w1024_n.png",
        price: "24,50$",
        description: "Beyaz çikolata sosu, espresso, buharla isitilmiş süt ve krema.", 
        calories: "45,56",
    },
       {
        restaurantName: "Starbucks, Bebek",
        foodName: "Caffè Americano",
        foodImage:"https://www.starbucks.com.tr/media/caffe-americano_tcm95-64116_w1024_n.png",
        price: "23,50$",
        description: "Yoğun espressonun sicak su ile inceltilmesi.", 
    },
         {
        categoryName: "Coffee",
        restaurantName: "Kahve Dünyasi",
        foodName: "White Chocolate Mocha",
        foodImage: "https://www.kahvedunyasi.co.uk/CMSFiles/Product/LittleImage/dark-chocolate-mocha_636482237710605582.jpg",
        restaurantImage: "https://i.dunya.com/2/1280/720/storage/old/files/2020/9/29/483384/483384.jpg.webp",
        restaurantRating: "4.0", 
        workingHours: "08.00-01.00", 
        price: "18,50$",
        rating: "4.5",
        tab: "Delivery",  
    },
         {
        categoryName: "Coffee",
        restaurantName: "Kahve Dünyasi",
        foodName: "White Chocolate Mocha",
        foodImage: "https://www.kahvedunyasi.co.uk/CMSFiles/Product/LittleImage/dark-chocolate-mocha_636482237710605582.jpg",
        restaurantImage: "https://i.dunya.com/2/1280/720/storage/old/files/2020/9/29/483384/483384.jpg.webp",
        restaurantRating: "4.0", 
        workingHours: "08.00-01.00", 
        price: "18,50$",
        rating: "4.5",
        tab: "Delivery",  
    },
         {
        categoryName: "Coffee",
        restaurantName: "Kahve Dünyasi",
        foodName: "White Chocolate Mocha",
        foodImage: "https://www.kahvedunyasi.co.uk/CMSFiles/Product/LittleImage/dark-chocolate-mocha_636482237710605582.jpg",
        restaurantImage: "https://i.dunya.com/2/1280/720/storage/old/files/2020/9/29/483384/483384.jpg.webp",
        restaurantRating: "4.0", 
        workingHours: "08.00-01.00", 
        price: "18,50$",
        rating: "4.5",
        tab: "Delivery",  
    },

    
    

    


];

export default Foods; 